# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'candy_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 674)
        MainWindow.setStyleSheet("")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.drone = QtWidgets.QGroupBox(MainWindow)
        self.drone.setObjectName("drone")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.drone)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.drone)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.drone_status_lbl = QtWidgets.QLabel(self.drone)
        self.drone_status_lbl.setStyleSheet("border-radius:10px; \n"
"background: red; \n"
"color: #4A0C46;\n"
"border: 1px solid black;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"min-width: 20px;\n"
"max-width: 20px;")
        self.drone_status_lbl.setText("")
        self.drone_status_lbl.setObjectName("drone_status_lbl")
        self.horizontalLayout_5.addWidget(self.drone_status_lbl)
        self.drone_refresh_btn = QtWidgets.QPushButton(self.drone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drone_refresh_btn.sizePolicy().hasHeightForWidth())
        self.drone_refresh_btn.setSizePolicy(sizePolicy)
        self.drone_refresh_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drone_refresh_btn.setIcon(icon)
        self.drone_refresh_btn.setObjectName("drone_refresh_btn")
        self.horizontalLayout_5.addWidget(self.drone_refresh_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.drone)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.drone_battery_gauge = QtWidgets.QProgressBar(self.drone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drone_battery_gauge.sizePolicy().hasHeightForWidth())
        self.drone_battery_gauge.setSizePolicy(sizePolicy)
        self.drone_battery_gauge.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: #000000;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: red;\n"
"     width: 20px;\n"
" }")
        self.drone_battery_gauge.setMaximum(100)
        self.drone_battery_gauge.setProperty("value", 80)
        self.drone_battery_gauge.setAlignment(QtCore.Qt.AlignCenter)
        self.drone_battery_gauge.setObjectName("drone_battery_gauge")
        self.horizontalLayout_6.addWidget(self.drone_battery_gauge)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.horizontalLayout_9.addWidget(self.drone)
        self.take_off_btn = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.take_off_btn.sizePolicy().hasHeightForWidth())
        self.take_off_btn.setSizePolicy(sizePolicy)
        self.take_off_btn.setMinimumSize(QtCore.QSize(200, 100))
        self.take_off_btn.setStyleSheet("background: green; ")
        self.take_off_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/takeoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("img/land.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.take_off_btn.setIcon(icon1)
        self.take_off_btn.setIconSize(QtCore.QSize(100, 100))
        self.take_off_btn.setObjectName("take_off_btn")
        self.horizontalLayout_9.addWidget(self.take_off_btn)
        self.controls = QtWidgets.QGroupBox(MainWindow)
        self.controls.setObjectName("controls")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.controls)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.arduino_discrete_radio = QtWidgets.QRadioButton(self.controls)
        self.arduino_discrete_radio.setMinimumSize(QtCore.QSize(70, 0))
        self.arduino_discrete_radio.setChecked(False)
        self.arduino_discrete_radio.setObjectName("arduino_discrete_radio")
        self.control_group = QtWidgets.QButtonGroup(MainWindow)
        self.control_group.setObjectName("control_group")
        self.control_group.addButton(self.arduino_discrete_radio)
        self.verticalLayout_2.addWidget(self.arduino_discrete_radio)
        self.arduino_continous_radio = QtWidgets.QRadioButton(self.controls)
        self.arduino_continous_radio.setMinimumSize(QtCore.QSize(70, 0))
        self.arduino_continous_radio.setChecked(False)
        self.arduino_continous_radio.setObjectName("arduino_continous_radio")
        self.control_group.addButton(self.arduino_continous_radio)
        self.verticalLayout_2.addWidget(self.arduino_continous_radio)
        self.line_3 = QtWidgets.QFrame(self.controls)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.riot_spin_radio = QtWidgets.QRadioButton(self.controls)
        self.riot_spin_radio.setMinimumSize(QtCore.QSize(70, 0))
        self.riot_spin_radio.setObjectName("riot_spin_radio")
        self.control_group.addButton(self.riot_spin_radio)
        self.verticalLayout_2.addWidget(self.riot_spin_radio)
        self.riot_energy_radio = QtWidgets.QRadioButton(self.controls)
        self.riot_energy_radio.setMinimumSize(QtCore.QSize(70, 0))
        self.riot_energy_radio.setChecked(True)
        self.riot_energy_radio.setObjectName("riot_energy_radio")
        self.control_group.addButton(self.riot_energy_radio)
        self.verticalLayout_2.addWidget(self.riot_energy_radio)
        self.horizontalLayout_16.addLayout(self.verticalLayout_2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.arduino_status_lbl = QtWidgets.QLabel(self.controls)
        self.arduino_status_lbl.setStyleSheet("border-radius:10px; \n"
"background:red; \n"
"color: #4A0C46;\n"
"border: 1px solid black;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"min-width: 20px;\n"
"max-width: 20px;")
        self.arduino_status_lbl.setText("")
        self.arduino_status_lbl.setObjectName("arduino_status_lbl")
        self.horizontalLayout_7.addWidget(self.arduino_status_lbl)
        self.arduino_refresh_btn = QtWidgets.QPushButton(self.controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arduino_refresh_btn.sizePolicy().hasHeightForWidth())
        self.arduino_refresh_btn.setSizePolicy(sizePolicy)
        self.arduino_refresh_btn.setText("")
        self.arduino_refresh_btn.setIcon(icon)
        self.arduino_refresh_btn.setObjectName("arduino_refresh_btn")
        self.horizontalLayout_7.addWidget(self.arduino_refresh_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.line_4 = QtWidgets.QFrame(self.controls)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_10.addWidget(self.line_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.riot_status_lbl = QtWidgets.QLabel(self.controls)
        self.riot_status_lbl.setStyleSheet("border-radius:10px; \n"
"background: red; \n"
"color: #4A0C46;\n"
"border: 1px solid black;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"min-width: 20px;\n"
"max-width: 20px;")
        self.riot_status_lbl.setText("")
        self.riot_status_lbl.setObjectName("riot_status_lbl")
        self.horizontalLayout_8.addWidget(self.riot_status_lbl)
        self.riot_refresh_button = QtWidgets.QPushButton(self.controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.riot_refresh_button.sizePolicy().hasHeightForWidth())
        self.riot_refresh_button.setSizePolicy(sizePolicy)
        self.riot_refresh_button.setText("")
        self.riot_refresh_button.setIcon(icon)
        self.riot_refresh_button.setObjectName("riot_refresh_button")
        self.horizontalLayout_8.addWidget(self.riot_refresh_button)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_16.addLayout(self.verticalLayout_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9.addWidget(self.controls)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tabs = QtWidgets.QTabWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setMinimumSize(QtCore.QSize(100, 240))
        self.tabs.setStyleSheet("")
        self.tabs.setObjectName("tabs")
        self.default = QtWidgets.QWidget()
        self.default.setObjectName("default")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.default)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.simple_mode = QtWidgets.QCheckBox(self.default)
        self.simple_mode.setObjectName("simple_mode")
        self.verticalLayout_11.addWidget(self.simple_mode)
        self.graphicsView = QtWidgets.QGraphicsView(self.default)
        self.graphicsView.setMinimumSize(QtCore.QSize(200, 300))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_11.addWidget(self.graphicsView)
        self.tabs.addTab(self.default, "")
        self.calibration = QtWidgets.QWidget()
        self.calibration.setObjectName("calibration")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.calibration)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.calib_arduino = QtWidgets.QGroupBox(self.calibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_arduino.sizePolicy().hasHeightForWidth())
        self.calib_arduino.setSizePolicy(sizePolicy)
        self.calib_arduino.setObjectName("calib_arduino")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.calib_arduino)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.calib_arduino)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.calib_arduino)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(80, 0))
        self.label_12.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.discrete_treshold_sld = QtWidgets.QSlider(self.calib_arduino)
        self.discrete_treshold_sld.setMaximum(100)
        self.discrete_treshold_sld.setOrientation(QtCore.Qt.Horizontal)
        self.discrete_treshold_sld.setObjectName("discrete_treshold_sld")
        self.horizontalLayout_17.addWidget(self.discrete_treshold_sld)
        self.discrete_treshold_spin = QtWidgets.QSpinBox(self.calib_arduino)
        self.discrete_treshold_spin.setMinimumSize(QtCore.QSize(60, 0))
        self.discrete_treshold_spin.setMaximum(100)
        self.discrete_treshold_spin.setObjectName("discrete_treshold_spin")
        self.horizontalLayout_17.addWidget(self.discrete_treshold_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.calib_arduino)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(80, 0))
        self.label_17.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.discrete_duration_sld = QtWidgets.QSlider(self.calib_arduino)
        self.discrete_duration_sld.setMinimum(200)
        self.discrete_duration_sld.setMaximum(5000)
        self.discrete_duration_sld.setSingleStep(100)
        self.discrete_duration_sld.setOrientation(QtCore.Qt.Horizontal)
        self.discrete_duration_sld.setObjectName("discrete_duration_sld")
        self.horizontalLayout_18.addWidget(self.discrete_duration_sld)
        self.discrete_duration_spin = QtWidgets.QSpinBox(self.calib_arduino)
        self.discrete_duration_spin.setMinimumSize(QtCore.QSize(60, 0))
        self.discrete_duration_spin.setMinimum(200)
        self.discrete_duration_spin.setMaximum(5000)
        self.discrete_duration_spin.setSingleStep(100)
        self.discrete_duration_spin.setProperty("value", 1000)
        self.discrete_duration_spin.setObjectName("discrete_duration_spin")
        self.horizontalLayout_18.addWidget(self.discrete_duration_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.range_layout = QtWidgets.QVBoxLayout()
        self.range_layout.setObjectName("range_layout")
        self.label = QtWidgets.QLabel(self.calib_arduino)
        self.label.setObjectName("label")
        self.range_layout.addWidget(self.label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.calib_arduino)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(self.calib_arduino)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.range_layout.addLayout(self.horizontalLayout_11)
        self.top_down_layout = QtWidgets.QHBoxLayout()
        self.top_down_layout.setObjectName("top_down_layout")
        self.range_layout.addLayout(self.top_down_layout)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_18 = QtWidgets.QLabel(self.calib_arduino)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_24.addWidget(self.label_18)
        self.label_22 = QtWidgets.QLabel(self.calib_arduino)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_24.addWidget(self.label_22)
        self.range_layout.addLayout(self.horizontalLayout_24)
        self.clock_anticlock_layout = QtWidgets.QHBoxLayout()
        self.clock_anticlock_layout.setObjectName("clock_anticlock_layout")
        self.range_layout.addLayout(self.clock_anticlock_layout)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_14 = QtWidgets.QLabel(self.calib_arduino)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_23.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.calib_arduino)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_23.addWidget(self.label_15)
        self.range_layout.addLayout(self.horizontalLayout_23)
        self.front_back_layout = QtWidgets.QHBoxLayout()
        self.front_back_layout.setObjectName("front_back_layout")
        self.range_layout.addLayout(self.front_back_layout)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_23 = QtWidgets.QLabel(self.calib_arduino)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_25.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.calib_arduino)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_25.addWidget(self.label_24)
        self.range_layout.addLayout(self.horizontalLayout_25)
        self.right_left_layout = QtWidgets.QHBoxLayout()
        self.right_left_layout.setObjectName("right_left_layout")
        self.range_layout.addLayout(self.right_left_layout)
        self.verticalLayout_12.addLayout(self.range_layout)
        self.horizontalLayout_19.addWidget(self.calib_arduino)
        self.line = QtWidgets.QFrame(self.calibration)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_19.addWidget(self.line)
        self.riot = QtWidgets.QGroupBox(self.calibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.riot.sizePolicy().hasHeightForWidth())
        self.riot.setSizePolicy(sizePolicy)
        self.riot.setObjectName("riot")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.riot)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.riot)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.riot_energy_gauge = QtWidgets.QProgressBar(self.riot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.riot_energy_gauge.sizePolicy().hasHeightForWidth())
        self.riot_energy_gauge.setSizePolicy(sizePolicy)
        self.riot_energy_gauge.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: #000000;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: #05B8CC;\n"
"     width: 20px;\n"
" }")
        self.riot_energy_gauge.setMaximum(100)
        self.riot_energy_gauge.setProperty("value", 80)
        self.riot_energy_gauge.setObjectName("riot_energy_gauge")
        self.horizontalLayout_20.addWidget(self.riot_energy_gauge)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.riot)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.riot_spin_gauge = QtWidgets.QProgressBar(self.riot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.riot_spin_gauge.sizePolicy().hasHeightForWidth())
        self.riot_spin_gauge.setSizePolicy(sizePolicy)
        self.riot_spin_gauge.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: #000000;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: #05B8CC;\n"
"     width: 20px;\n"
" }")
        self.riot_spin_gauge.setMaximum(100)
        self.riot_spin_gauge.setProperty("value", 80)
        self.riot_spin_gauge.setObjectName("riot_spin_gauge")
        self.horizontalLayout_21.addWidget(self.riot_spin_gauge)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19.addWidget(self.riot)
        self.tabs.addTab(self.calibration, "")
        self.verticalLayout_4.addWidget(self.tabs)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.presets = QtWidgets.QGroupBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presets.sizePolicy().hasHeightForWidth())
        self.presets.setSizePolicy(sizePolicy)
        self.presets.setObjectName("presets")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.presets)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.presets_listView = QtWidgets.QListView(self.presets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presets_listView.sizePolicy().hasHeightForWidth())
        self.presets_listView.setSizePolicy(sizePolicy)
        self.presets_listView.setMinimumSize(QtCore.QSize(200, 0))
        self.presets_listView.setObjectName("presets_listView")
        self.verticalLayout_6.addWidget(self.presets_listView)
        self.save_as_btn = QtWidgets.QPushButton(self.presets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_as_btn.sizePolicy().hasHeightForWidth())
        self.save_as_btn.setSizePolicy(sizePolicy)
        self.save_as_btn.setObjectName("save_as_btn")
        self.verticalLayout_6.addWidget(self.save_as_btn)
        self.logos = QtWidgets.QHBoxLayout()
        self.logos.setObjectName("logos")
        self.enac_logo = QtWidgets.QLabel(self.presets)
        self.enac_logo.setMaximumSize(QtCore.QSize(80, 80))
        self.enac_logo.setText("")
        self.enac_logo.setPixmap(QtGui.QPixmap("img/ENAC-Bleu.png"))
        self.enac_logo.setScaledContents(True)
        self.enac_logo.setObjectName("enac_logo")
        self.logos.addWidget(self.enac_logo)
        self.candy_logo = QtWidgets.QLabel(self.presets)
        self.candy_logo.setMaximumSize(QtCore.QSize(80, 80))
        self.candy_logo.setText("")
        self.candy_logo.setPixmap(QtGui.QPixmap("img/candyfly-logo.png"))
        self.candy_logo.setScaledContents(True)
        self.candy_logo.setObjectName("candy_logo")
        self.logos.addWidget(self.candy_logo)
        self.verticalLayout_6.addLayout(self.logos)
        self.horizontalLayout_13.addWidget(self.presets)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_13)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.speeds = QtWidgets.QGroupBox(MainWindow)
        self.speeds.setMaximumSize(QtCore.QSize(16777215, 160))
        self.speeds.setObjectName("speeds")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.speeds)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.speeds)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.vert_speed_sld = QtWidgets.QSlider(self.speeds)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vert_speed_sld.sizePolicy().hasHeightForWidth())
        self.vert_speed_sld.setSizePolicy(sizePolicy)
        self.vert_speed_sld.setMinimumSize(QtCore.QSize(200, 0))
        self.vert_speed_sld.setMinimum(10)
        self.vert_speed_sld.setMaximum(300)
        self.vert_speed_sld.setOrientation(QtCore.Qt.Horizontal)
        self.vert_speed_sld.setObjectName("vert_speed_sld")
        self.horizontalLayout_2.addWidget(self.vert_speed_sld)
        self.vert_speed_spin = QtWidgets.QDoubleSpinBox(self.speeds)
        self.vert_speed_spin.setMinimum(0.1)
        self.vert_speed_spin.setMaximum(3.0)
        self.vert_speed_spin.setObjectName("vert_speed_spin")
        self.horizontalLayout_2.addWidget(self.vert_speed_spin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.speeds)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.horiz_speed_sld = QtWidgets.QSlider(self.speeds)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horiz_speed_sld.sizePolicy().hasHeightForWidth())
        self.horiz_speed_sld.setSizePolicy(sizePolicy)
        self.horiz_speed_sld.setMinimumSize(QtCore.QSize(200, 0))
        self.horiz_speed_sld.setMinimum(10)
        self.horiz_speed_sld.setMaximum(300)
        self.horiz_speed_sld.setOrientation(QtCore.Qt.Horizontal)
        self.horiz_speed_sld.setObjectName("horiz_speed_sld")
        self.horizontalLayout.addWidget(self.horiz_speed_sld)
        self.horiz_speed_spin = QtWidgets.QDoubleSpinBox(self.speeds)
        self.horiz_speed_spin.setMinimum(0.1)
        self.horiz_speed_spin.setMaximum(3.0)
        self.horiz_speed_spin.setObjectName("horiz_speed_spin")
        self.horizontalLayout.addWidget(self.horiz_speed_spin)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.speeds)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.rot_speed_sld = QtWidgets.QSlider(self.speeds)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rot_speed_sld.sizePolicy().hasHeightForWidth())
        self.rot_speed_sld.setSizePolicy(sizePolicy)
        self.rot_speed_sld.setMinimumSize(QtCore.QSize(200, 0))
        self.rot_speed_sld.setMinimum(10)
        self.rot_speed_sld.setMaximum(360)
        self.rot_speed_sld.setOrientation(QtCore.Qt.Horizontal)
        self.rot_speed_sld.setObjectName("rot_speed_sld")
        self.horizontalLayout_3.addWidget(self.rot_speed_sld)
        self.rot_speed_spin = QtWidgets.QSpinBox(self.speeds)
        self.rot_speed_spin.setMinimum(10)
        self.rot_speed_spin.setMaximum(360)
        self.rot_speed_spin.setObjectName("rot_speed_spin")
        self.horizontalLayout_3.addWidget(self.rot_speed_spin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addWidget(self.speeds)
        self.comments = QtWidgets.QGroupBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments.sizePolicy().hasHeightForWidth())
        self.comments.setSizePolicy(sizePolicy)
        self.comments.setMaximumSize(QtCore.QSize(16777215, 160))
        self.comments.setObjectName("comments")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.comments)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.comment_textEdit = QtWidgets.QTextEdit(self.comments)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_textEdit.sizePolicy().hasHeightForWidth())
        self.comment_textEdit.setSizePolicy(sizePolicy)
        self.comment_textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.comment_textEdit.setObjectName("comment_textEdit")
        self.horizontalLayout_14.addWidget(self.comment_textEdit)
        self.horizontalLayout_4.addWidget(self.comments)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.discrete_treshold_spin.valueChanged['int'].connect(self.discrete_treshold_sld.setValue)
        self.discrete_treshold_sld.valueChanged['int'].connect(self.discrete_treshold_spin.setValue)
        self.discrete_duration_spin.valueChanged['int'].connect(self.discrete_duration_sld.setValue)
        self.discrete_duration_sld.valueChanged['int'].connect(self.discrete_duration_spin.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CandyFly"))
        self.drone.setTitle(_translate("MainWindow", "Drone"))
        self.label_13.setText(_translate("MainWindow", "Connection: "))
        self.label_11.setText(_translate("MainWindow", "Battery"))
        self.controls.setTitle(_translate("MainWindow", "Contrôleurs"))
        self.arduino_discrete_radio.setText(_translate("MainWindow", "Arduino Discret"))
        self.arduino_continous_radio.setText(_translate("MainWindow", "Arduino Continu"))
        self.riot_spin_radio.setText(_translate("MainWindow", "Riot Rotation"))
        self.riot_energy_radio.setText(_translate("MainWindow", "Riot Energie"))
        self.simple_mode.setText(_translate("MainWindow", "Simplifié"))
        self.tabs.setTabText(self.tabs.indexOf(self.default), _translate("MainWindow", "Controles"))
        self.calib_arduino.setTitle(_translate("MainWindow", "Arduino"))
        self.label_10.setText(_translate("MainWindow", "Réglage mode discret"))
        self.label_12.setText(_translate("MainWindow", "Seuil (%)"))
        self.label_17.setText(_translate("MainWindow", "Durée (ms)"))
        self.label.setText(_translate("MainWindow", "Force sensors"))
        self.label_6.setText(_translate("MainWindow", "Haut"))
        self.label_2.setText(_translate("MainWindow", "Bas"))
        self.label_18.setText(_translate("MainWindow", "Horaire"))
        self.label_22.setText(_translate("MainWindow", "Anti-horaire"))
        self.label_14.setText(_translate("MainWindow", "Avant"))
        self.label_15.setText(_translate("MainWindow", "Arriere"))
        self.label_23.setText(_translate("MainWindow", "Droite"))
        self.label_24.setText(_translate("MainWindow", "Gauche"))
        self.riot.setTitle(_translate("MainWindow", "Riot"))
        self.label_20.setText(_translate("MainWindow", "Energie"))
        self.label_21.setText(_translate("MainWindow", "Rotation"))
        self.tabs.setTabText(self.tabs.indexOf(self.calibration), _translate("MainWindow", "Calibration"))
        self.presets.setTitle(_translate("MainWindow", "Presets"))
        self.save_as_btn.setText(_translate("MainWindow", "Enregistrer Sous"))
        self.speeds.setTitle(_translate("MainWindow", "Vitesses"))
        self.label_3.setText(_translate("MainWindow", "Verticale (m/s)"))
        self.label_4.setText(_translate("MainWindow", "Horizontale (m/s)"))
        self.label_5.setText(_translate("MainWindow", "Rotation (°/s)"))
        self.comments.setTitle(_translate("MainWindow", "Commentaires"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
